### ISSUE TITLE
`latest` tag in auto-mode is applied to older major versions

### ISSUE THREAD

**Issue by dersimn** [docker/metadata-action#326]
#### Steps to reproduce this issue

1. Create a Repo, with Docker Meta Action, like [this](https://github.com/dersimn/HelloARM-GitHub-Workflow/blob/3eb8ddf28d9c36e3d245dc3755ee42098f6db46d/.github/workflows/docker.yml#L19).
2. Push Tag "v2.5.2", this will create Docker Tags `2`, `2.5`, `2.5.2`, `latest` as expected. See [here](https://github.com/dersimn/HelloARM-GitHub-Workflow/actions/runs/6057404050/job/16438523468#step:3:47).
3. Push Tag "v1.1.1", this will create Docker Tags `1`, `1.1`, `1.1.1` and also `latest`, which is wrong, because the latest version would still be v2.5.3. See [here](https://github.com/dersimn/HelloARM-GitHub-Workflow/actions/runs/6057412391/job/16438542647#step:3:47).

This happens with every tag push where the major version doesn't match. For e.g. pushing v2.5.3 and then v2.1.3 works as expected. idk, if this is the intended behaviour, but if you'd retro-fit an older version with some update the `latest` tag shouldn't be overwritten.

### Configuration

* Repository URL (if public): https://github.com/dersimn/HelloARM-GitHub-Workflow
* Build URL (if public): https://hub.docker.com/repository/docker/dersimn/helloarm-github-workflow

**Comment by crazy-max** [comment]
> idk, if this is the intended behaviour

This is the expected behavior, see https://github.com/docker/metadata-action#latest-tag

You should have a condition on setting latest only for latest release (`v2` in your case). I have this kind of pattern in https://github.com/crazy-max/docker-nextcloud/blob/c9a16f5914faae0f36caaea0290d41cbe8914f37/.github/workflows/build.yml#L56

In your case:

```yaml
flavor: |
  latest=${{ startsWith(github.ref, 'refs/tags/v2') }}
```

**Comment by douglasparker** [comment]
> > idk, if this is the intended behaviour
> 
> This is the expected behavior, see https://github.com/docker/metadata-action#latest-tag
> 
> You should have a condition on setting latest only for latest release (`v2` in your case). I have this kind of pattern in https://github.com/crazy-max/docker-nextcloud/blob/c9a16f5914faae0f36caaea0290d41cbe8914f37/.github/workflows/build.yml#L56
> 
> In your case:
> 
> ```yaml
> flavor: |
>   latest=${{ startsWith(github.ref, 'refs/tags/v2') }}
> ```

Is there a better way to handle this?

I was following this issue because I'd like to avoid having to update the workflow for ever new major version release.

It would be much better if this action was smarter about the usage of the latest tag.

Why make people go through the extra work? 2.0 is greater than 1.0.

Backporting a bug fix should not update the latest tag to an older version...
